Feat: New mutation allowing leader of the beacon to change duration.
CCExtractor/beacon-backend pull request #84
Opened 2022-01-14 20:08 UTC by Aadeesh11

Fixes: #71 

Changes Made: 
Add a new mutation that performs some checks, and then changes the duration of the beacon.

2022-01-14 20:11 UTC, Aadeesh11 commented
@aadibajpai i have tested this locally as well !

2022-01-17 10:15 UTC, Aadeesh11 commented
@aadibajpai anything else needs to be done?

2022-01-21 11:12 UTC, Aadeesh11 commented
Can we merge this @aadibajpai, or something else needs to be done?

2022-01-21 15:38 UTC, aadibajpai commented on graphql/resolvers.js
> +            if (beacon.leader.id != user.id)
can you not use strict inequality here?

2022-01-22 08:32 UTC, Aadeesh11 commented on graphql/resolvers.js
> +            if (beacon.leader.id != user.id)
I have made the required changes.

2022-01-25 10:05 UTC, Aadeesh11 commented
Can we merge this @aadibajpai ?

2022-01-25 15:28 UTC, aadibajpai commented on graphql/resolvers.js
> +            if (beacon.leader.id != user.id)
@Aadeesh11 so I looked more into this and there is some current code that does not actually use strict inequality. I assume you copied from there. That is correct bc they have different types here so you should probably revert it. Then it can be merged.

2022-01-25 17:08 UTC, aadibajpai requested changes
​

2022-01-25 19:15 UTC, Aadeesh11 commented on graphql/resolvers.js
> +            if (beacon.leader.id != user.id)
Sure.

2022-01-25 19:16 UTC, Aadeesh11 commented
Reverted the change.

2022-01-25 19:45 UTC, merged

2022-01-25 22:07 UTC, Aadeesh11 commented
@aadibajpai when would the changes be reflected in the playground?